#!/bin/bash

## Before running:
# This tool requires to have solc installed.
# Ensure that you have the binaries installed by pip3 in your path.
# Install: https://github.com/crytic/slither#how-to-install
# Usage: https://github.com/crytic/slither/wiki/Usage

mkdir -p reports

docker run \
    --name slither-analysis \
    -v $(pwd):/app/bookadot-smart-contract \
    trailofbits/eth-security-toolbox \
    slither /app/bookadot-smart-contract \
    &> reports/slither-analyzer-report.log

docker rm slither-analysis

echo "Slither analyzed"
echo "Done"